# This modifies the bounding box, This is stuff like can a arrow hit them.
# If you turn this to true, arrows will act like they hit the disguise in the right place!
# Clients will not see any difference in the hitboxes they are attacking, this is a server-sided calculation!
# So someone disguised as a enderdragon will easily get shot down by arrows!
# This WILL conflict with NoCheatPlus. Other plugins may also get problems.
# This shouldn't really be enabled for players as it also interferes with their movement because the server thinks
# the player is larger than they really are.
# That makes the player unable to approach this building because the server thinks they are trying to glitch inside
# blocks.
# This feature is highly experimental and is guaranteed to cause problems for players who are disguised
ModifyBoundingBox: false

# On player disguise, a fake player is added to tablist so the skin can load properly.
# This option is ignored if 'ShowPlayerDisguisesInTab' is enabled.
# How many ticks before tab packet is sent to remove from tablist. This shouldn't need to be touched
TablistRemoveDelay: 3

# To prevent skins from defaulting to alex/steve, there is a timer that only expires after X ticks or when the player moves
# You shouldn't actually touch this, but eh. Your server.
# Default is 5 seconds
PlayerDisguisesTablistExpiresMove: 100

Ticker:
  # This setting controls if Lib's Disguises will tell Minecraft to send more packet updates of every tiny movement.
  # Used on 1.21.5+ when a projectile is disguised as a non-projectile, to ensure that the movement looks smoother, as
  # normal projectiles expect the client to render the movement, while other entities expect the server to tell the
  # client of the movement.
  # Which means, clients would see a disguised arrow only moving every few seconds.
  # The above may apply to more non-living entities, but it's mainly projectiles we're concerned about.
  # A projectile that has no velocity, will be ignored. Unless a projectile is not vanilla, it shouldn't matter.
  # To restore vanilla functionality, set this to false. Lib's Disguises has default 'true'
  Projectiles: true

# What disguise types are default to OP only, because they are prone to abuse.
# By default, this contains TEXT_DISPLAY, ITEM_DISPLAY, BLOCK_DISPLAY and INTERACTION
DisabledDisguises:
  - TEXT_DISPLAY
  - ITEM_DISPLAY
  - BLOCK_DISPLAY
  - INTERACTION

# These disguise methods are also limited to OP only, because they're open to abuse
# setInvisible has overlap with the config option for disabled invisibility, if either is used, it will be disabled.
# Thankfully, only trusted people are OP. So this doesn't need further configuration.
# Command users who has the permission return true for "libsdisguises.*.*.*" will also have access.
DisabledMethods:
  - setYModifier
  - setNameYModifier
  - setInvisible
  - setUnsafeSize
  - setScalePlayerToDisguise