package me.libraryaddict.disguise.disguisetypes;

import com.github.retrooper.packetevents.PacketEvents;
import com.github.retrooper.packetevents.protocol.attribute.Attributes;
import com.github.retrooper.packetevents.wrapper.PacketWrapper;
import com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerPlayerInfo;
import com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerUpdateAttributes;
import lombok.Getter;
import lombok.Setter;
import me.libraryaddict.disguise.DisguiseAPI;
import me.libraryaddict.disguise.DisguiseConfig;
import me.libraryaddict.disguise.LibsDisguises;
import me.libraryaddict.disguise.disguisetypes.TargetedDisguise.TargetType;
import me.libraryaddict.disguise.disguisetypes.watchers.AbstractHorseWatcher;
import me.libraryaddict.disguise.disguisetypes.watchers.AgeableWatcher;
import me.libraryaddict.disguise.disguisetypes.watchers.BoatWatcher;
import me.libraryaddict.disguise.disguisetypes.watchers.LivingWatcher;
import me.libraryaddict.disguise.disguisetypes.watchers.SheepWatcher;
import me.libraryaddict.disguise.disguisetypes.watchers.ZombieWatcher;
import me.libraryaddict.disguise.events.DisguiseEvent;
import me.libraryaddict.disguise.events.UndisguiseEvent;
import me.libraryaddict.disguise.utilities.DisguiseUtilities;
import me.libraryaddict.disguise.utilities.LibsPremium;
import me.libraryaddict.disguise.utilities.parser.AutoGeneratedValue;
import me.libraryaddict.disguise.utilities.reflection.NmsVersion;
import me.libraryaddict.disguise.utilities.reflection.ReflectionManager;
import me.libraryaddict.disguise.utilities.translations.LibsMsg;
import net.md_5.bungee.api.ChatMessageType;
import net.md_5.bungee.api.chat.BaseComponent;
import org.bukkit.Bukkit;
import org.bukkit.attribute.AttributeInstance;
import org.bukkit.attribute.AttributeModifier;
import org.bukkit.boss.BarColor;
import org.bukkit.boss.BarStyle;
import org.bukkit.boss.BossBar;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.AbstractHorse;
import org.bukkit.entity.Boat;
import org.bukkit.entity.Entity;
import org.bukkit.entity.FallingBlock;
import org.bukkit.entity.Item;
import org.bukkit.entity.LivingEntity;
import org.bukkit.entity.Player;
import org.bukkit.inventory.EquipmentSlotGroup;
import org.bukkit.metadata.FixedMetadataValue;
import org.bukkit.scheduler.BukkitRunnable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Random;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

public abstract class Disguise {
    /**
     * In use doesn't mean that this disguise is active. It means that Lib's Disguises still stores a reference to
     * the disguise. Though it also means the disguise is active.
     * getEntity() can still return null if this disguise is active after despawn, logout, etc.
     *
     * @return isDisguiseInUse
     */
    @Getter
    private transient boolean disguiseInUse;
    private final DisguiseType disguiseType;
    private transient BukkitRunnable runnable;
    /**
     * The entity that is disguised
     */
    @Getter
    private transient Entity entity;
    @Getter
    private boolean hearSelfDisguise = DisguiseConfig.isSelfDisguisesSoundsReplaced();
    @Getter
    private boolean hideArmorFromSelf = DisguiseConfig.isHidingArmorFromSelf();
    @Getter
    private boolean hideHeldItemFromSelf = DisguiseConfig.isHidingHeldItemFromSelf();
    @Getter
    private boolean keepDisguiseOnPlayerDeath = DisguiseConfig.isKeepDisguiseOnPlayerDeath();
    @Getter
    private boolean modifyBoundingBox = DisguiseConfig.isModifyBoundingBox();
    private boolean playerHiddenFromTab = DisguiseConfig.isHideDisguisedPlayers();
    private boolean replaceSounds = DisguiseConfig.isSoundEnabled();
    @Setter
    @Getter
    private boolean mobsIgnoreDisguise;
    @Getter
    private boolean velocitySent = DisguiseConfig.isVelocitySent();
    private boolean viewSelfDisguise = DisguiseConfig.isViewDisguises() && DisguiseConfig.isViewSelfDisguisesDefault();
    @Getter
    private DisguiseConfig.NotifyBar notifyBar = DisguiseConfig.getNotifyBar();
    @Getter
    private BarColor bossBarColor = DisguiseConfig.getBossBarColor();
    @Getter
    private BarStyle bossBarStyle = DisguiseConfig.getBossBarStyle();
    /**
     * The unique FlagWatcher of this disguise
     */
    @Getter
    private FlagWatcher watcher;
    /**
     * If set, how long before disguise expires
     */
    protected long disguiseExpires;
    /**
     * For when plugins may want to assign custom data to a disguise, such as who owns it
     */
    private final LinkedHashMap<String, Object> customData = new LinkedHashMap<>();
    @Getter
    private String disguiseName;
    /**
     * Is the name specifically set to something by a third party?
     */
    @Getter
    @Setter
    private boolean customDisguiseName = false;
    @Getter
    @Setter
    private boolean tallDisguisesVisible = DisguiseConfig.isTallSelfDisguises();
    private String[] multiName = new String[0];
    private transient int[] armorstandIds = new int[0];
    @Getter
    @Setter
    private boolean dynamicName;
    @Getter
    @Setter
    private String soundGroup;
    private UUID uuid = ReflectionManager.getRandomUUID();
    @Getter
    private boolean scalePlayerToDisguise = DisguiseConfig.isScaleSelfDisguises();
    @Getter
    private final DisguiseInternals internals;

    public Disguise(DisguiseType disguiseType) {
        this.disguiseType = disguiseType;
        this.disguiseName = disguiseType.toReadable();
        this.internals = new DisguiseInternals(this);
    }

    public HashMap<String, Object> getCustomData() {
        return customData;
    }

    public UUID getUUID() {
        // If this is not a player disguise, or it is but we're not trying to make sure its unique
        if (!isPlayerDisguise() || !DisguiseConfig.isUniquePlayerDisguiseUUIDs()) {
            if (!DisguiseConfig.isRandomUUIDS() && getEntity() != null) {
                return getEntity().getUniqueId();
            }
        }

        // Partial fix for disguises serialized in older versions
        if (this.uuid == null) {
            this.uuid = ReflectionManager.getRandomUUID();
        }

        return uuid;
    }

    public int getMultiNameLength() {
        return multiName.length;
    }

    @AutoGeneratedValue
    public void setDisguiseName(String name) {
        this.disguiseName = name;
    }

    /**
     * Gson why you so dumb and set it to null
     */
    private int[] getInternalArmorstandIds() {
        if (armorstandIds == null) {
            armorstandIds = new int[0];
        }

        return armorstandIds;
    }

    public String[] getMultiName() {
        return DisguiseUtilities.reverse(multiName);
    }

    public void setMultiName(String... name) {
        if (name.length == 1 && name[0].isEmpty()) {
            name = new String[0];
        }

        for (int i = 0; i < name.length; i++) {
            name[i] = DisguiseUtilities.getHexedColors(name[i]);
        }

        name = DisguiseUtilities.reverse(name);

        String[] oldName = multiName;
        multiName = name;

        if (Arrays.equals(oldName, name)) {
            return;
        }

        if (!isDisguiseInUse()) {
            return;
        }

        sendArmorStands(oldName);
    }

    public abstract double getHeight();

    public double getNameHeightScale() {
        if (!NmsVersion.v1_20_R4.isSupported() || isMiscDisguise()) {
            return 1;
        }

        double finalScale;
        Double watcherScale = getWatcher() instanceof LivingWatcher ? ((LivingWatcher) getWatcher()).getScale() : null;

        if (watcherScale != null) {
            finalScale = watcherScale;
        } else {
            finalScale = getInternals().getEntityScaleWithoutLibsDisguises();
        }

        // Clamp
        if (finalScale < 0.06) {
            finalScale = 0.06;
        } else if (finalScale > 16) {
            finalScale = 16;
        }

        return finalScale;
    }

    protected void sendArmorStands(String[] oldName) {
        if (!isDisguiseInUse()) {
            return;
        }

        adjustTallSelfDisguiseScale();

        for (Player player : DisguiseUtilities.getPerverts(this)) {
            if (!DisguiseUtilities.isFancyHiddenTabs() && isPlayerDisguise() &&
                LibsDisguises.getInstance().getSkinHandler().isSleeping(player, (PlayerDisguise) this)) {
                continue;
            }

            List<PacketWrapper<?>> packets = DisguiseUtilities.getNamePackets(this, player, oldName);

            for (PacketWrapper<?> packet : packets) {
                PacketEvents.getAPI().getPlayerManager().sendPacket(player, packet);
            }
        }
    }

    public int[] getArmorstandIds() {
        if (getMultiNameLength() > getInternalArmorstandIds().length) {
            int oldLen = armorstandIds.length;

            armorstandIds = Arrays.copyOf(armorstandIds, getMultiNameLength());

            for (int i = oldLen; i < armorstandIds.length; i++) {
                armorstandIds[i] = ReflectionManager.getNewEntityId();
            }
        }

        return armorstandIds;
    }

    public void addCustomData(String key, Object data) {
        customData.put(key, data);
    }

    public boolean hasCustomData(String key) {
        return customData.containsKey(key);
    }

    public Object getCustomData(String key) {
        return customData.get(key);
    }

    @Override
    public abstract Disguise clone();

    protected void clone(Disguise disguise) {
        disguise.setDisguiseName(getDisguiseName());
        disguise.setCustomDisguiseName(isCustomDisguiseName());
        disguise.setTallDisguisesVisible(isTallDisguisesVisible());

        disguise.setReplaceSounds(isSoundsReplaced());
        disguise.setViewSelfDisguise(isSelfDisguiseVisible());
        disguise.setHearSelfDisguise(isSelfDisguiseSoundsReplaced());
        disguise.setHideArmorFromSelf(isHidingArmorFromSelf());
        disguise.setHideHeldItemFromSelf(isHidingHeldItemFromSelf());
        disguise.setVelocitySent(isVelocitySent());
        disguise.setModifyBoundingBox(isModifyBoundingBox());
        disguise.multiName = Arrays.copyOf(multiName, multiName.length);
        disguise.setDynamicName(isDynamicName());
        disguise.setSoundGroup(getSoundGroup());
        disguise.notifyBar = getNotifyBar();
        disguise.bossBarColor = getBossBarColor();
        disguise.bossBarStyle = getBossBarStyle();
        disguise.setExpires(getExpires());

        if (getWatcher() != null) {
            disguise.setWatcher(getWatcher().clone(disguise));
        }

        disguise.createDisguise();
    }

    /**
     * Seems I do this method so I can make cleaner constructors on disguises..
     */
    protected void createDisguise() {
        if (getType().getEntityType() == null) {
            throw new RuntimeException("DisguiseType " + getType() +
                " was used in a futile attempt to construct a disguise, but this Minecraft version does not have " + "that entity");
        }

        // Get if they are a adult now..

        boolean isAdult = true;

        if (this instanceof MobDisguise) {
            isAdult = ((MobDisguise) this).isAdult();
        }

        if (getWatcher() == null) {
            try {
                // Construct the FlagWatcher from the stored class
                setWatcher(getType().getWatcherClass().getConstructor(Disguise.class).newInstance(this));
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (getWatcher().getDisguise() != this) {
            getWatcher().setDisguise((TargetedDisguise) this);
        }

        // Set the disguise if its a baby or not
        if (!isAdult) {
            if (getWatcher() instanceof AgeableWatcher) {
                ((AgeableWatcher) getWatcher()).setBaby(true);
            } else if (getWatcher() instanceof ZombieWatcher) {
                ((ZombieWatcher) getWatcher()).setBaby(true);
            }
        }
    }

    public boolean isDisguiseExpired() {
        return DisguiseConfig.isDynamicExpiry() ? disguiseExpires == 1 :
            disguiseExpires > 0 && disguiseExpires < System.currentTimeMillis();
    }

    public long getExpires() {
        return disguiseExpires;
    }

    public void setExpires(long timeToExpire) {
        disguiseExpires = timeToExpire;

        if (isDisguiseExpired()) {
            removeDisguise();
        }
    }

    private void removeBossBar() {
        BossBar bossBar = Bukkit.getBossBar(getInternals().getBossBar());

        if (bossBar == null) {
            return;
        }

        bossBar.removeAll();
        Bukkit.removeBossBar(getInternals().getBossBar());
    }

    public void setNotifyBar(DisguiseConfig.NotifyBar bar) {
        if (getNotifyBar() == bar) {
            return;
        }

        if (getNotifyBar() == DisguiseConfig.NotifyBar.BOSS_BAR) {
            removeBossBar();
        }

        this.notifyBar = bar;

        makeBossBar();
    }

    public void setBossBarColor(BarColor color) {
        if (getBossBarColor() == color) {
            return;
        }

        this.bossBarColor = color;

        makeBossBar();
    }

    public void setBossBarStyle(BarStyle style) {
        if (getBossBarStyle() == style) {
            return;
        }

        this.bossBarStyle = style;

        makeBossBar();
    }

    public void setBossBar(BarColor color, BarStyle style) {
        this.bossBarColor = color;
        this.bossBarStyle = style;

        setNotifyBar(DisguiseConfig.NotifyBar.BOSS_BAR);
    }

    private void makeBossBar() {
        if (getNotifyBar() != DisguiseConfig.NotifyBar.BOSS_BAR || !NmsVersion.v1_13.isSupported() || !(getEntity() instanceof Player)) {
            return;
        }

        if (getEntity().hasPermission("libsdisguises.noactionbar") || DisguiseAPI.getDisguise(getEntity()) != this) {
            return;
        }

        if (!DisguiseAPI.isNotifyBarShown(getEntity())) {
            return;
        }

        removeBossBar();

        BossBar bar = Bukkit.createBossBar(getInternals().getBossBar(),
            BaseComponent.toLegacyText(LibsMsg.ACTION_BAR_MESSAGE.getBase(getDisguiseName())), getBossBarColor(), getBossBarStyle());
        bar.setProgress(1);
        bar.addPlayer((Player) getEntity());
    }

    public boolean isUpsideDown() {
        return getWatcher() != null && getWatcher().isUpsideDown();
    }

    public Disguise setUpsideDown(boolean upsideDown) {
        getWatcher().setUpsideDown(upsideDown);

        return this;
    }

    protected void doPeriodicTick() {
        if (getNotifyBar() == DisguiseConfig.NotifyBar.ACTION_BAR && getEntity() instanceof Player &&
            DisguiseAPI.isNotifyBarShown(getEntity()) && !getEntity().hasPermission("libsdisguises.noactionbar") &&
            DisguiseAPI.getDisguise(getEntity()) == Disguise.this) {
            ((Player) getEntity()).spigot().sendMessage(ChatMessageType.ACTION_BAR, LibsMsg.ACTION_BAR_MESSAGE.getBase(getDisguiseName()));
        }

        if (isDynamicName()) {
            String name;

            if (getEntity() instanceof Player) {
                name = DisguiseUtilities.translateAlternateColorCodes(DisguiseUtilities.getDisplayName(getEntity()));
            } else {
                name = getEntity().getCustomName();
            }

            if (name == null) {
                name = "";
            }

            if (isPlayerDisguise()) {
                if (!((PlayerDisguise) Disguise.this).getName().equals(name)) {
                    ((PlayerDisguise) Disguise.this).setName(name);
                }
            } else {
                getWatcher().setCustomName(name);
            }
        }
    }

    private void createRunnable() {
        if (runnable != null && !runnable.isCancelled()) {
            runnable.cancel();
        }

        final TargetedDisguise disguise = (TargetedDisguise) this;

        // A scheduler to clean up any unused disguises.
        runnable = new DisguiseRunnable(this);

        runnable.runTaskTimer(LibsDisguises.getInstance(), 1, 1);
    }

    /**
     * Set the entity of the disguise. Only used for internal things.
     *
     * @param entity
     * @return disguise
     */
    public Disguise setEntity(Entity entity) {
        if (getEntity() != null) {
            if (getEntity() == entity) {
                return this;
            }

            throw new RuntimeException("This disguise is already in use! Try .clone()");
        }

        if (isMiscDisguise() && !DisguiseConfig.isMiscDisguisesForLivingEnabled() && entity instanceof LivingEntity) {
            throw new RuntimeException(
                "Cannot disguise a living entity with a misc disguise. Reenable MiscDisguisesForLiving in the " + "config to do this");
        }

        this.entity = entity;

        if (entity != null) {
            setupWatcher();
        }

        if (getEntity() instanceof Player && isSelfDisguiseVisible() && !isTallDisguisesVisible() && isTallDisguise()) {
            if (DisguiseConfig.isTallSelfDisguisesScaling() && NmsVersion.v1_20_R4.isSupported() && canScaleDisguise()) {
                adjustTallSelfDisguiseScale();
            } else {
                setSelfDisguiseVisible(false);
            }
        }

        return this;
    }

    private boolean isTallDisguise() {
        return DisguiseUtilities.isTallDisguise(this);
    }

    protected boolean canScaleDisguise() {
        return NmsVersion.v1_20_R4.isSupported() && !isMiscDisguise() && getType() != DisguiseType.ENDER_DRAGON;
    }

    public void setScalePlayerToDisguise(boolean scalePlayerToDisguise) {
        if (!LibsPremium.isPremium() && !DisguiseConfig.isScaleSelfDisguises() && scalePlayerToDisguise) {
            scalePlayerToDisguise = false;
            LibsDisguises.getInstance().getLogger()
                .info("You cannot use setScalePlayerToDisguise if it's disabled in the config without the Premium Plugin");
        }

        this.scalePlayerToDisguise = scalePlayerToDisguise;
        adjustTallSelfDisguiseScale();
    }

    protected void adjustTallSelfDisguiseScale() {
        if (!canScaleDisguise() || !isDisguiseInUse() || getEntity() == null) {
            return;
        }

        // TODO Extract this into DisguiseUtilities so that junit tests can be setup

        // Get the scale, default to "not scaled" if not a player
        double playerScaleWithoutLibsDisguises = getInternals().getEntityScaleWithoutLibsDisguises();
        // This is the height of the disguise, along with the name height
        double naturalHeightOfDisguise = getHeight();
        double increasedNaturalHeightOfDisguise = getHeight() * getNameHeightScale();

        if (DisguiseUtilities.isTallDisguise(this)) {
            increasedNaturalHeightOfDisguise *= 1.2;
        }

        // Here we have the scale of the player itself, where they'd be scaled up or down to match the disguise's scale
        // So a disguise that's 0.5 blocks high, will have the player be given something like 0.33 scale
        double scalerToMakePlayerSeePerspective = 1;

        if (isScalePlayerToDisguise()) {
            scalerToMakePlayerSeePerspective = naturalHeightOfDisguise / (1.8 * playerScaleWithoutLibsDisguises);

            // Clamp the scale to the min and max
            scalerToMakePlayerSeePerspective = Math.min(scalerToMakePlayerSeePerspective, DisguiseConfig.getScaleSelfDisguisesMax());
            scalerToMakePlayerSeePerspective = Math.max(scalerToMakePlayerSeePerspective, DisguiseConfig.getScaleSelfDisguisesMin());
        }

        // The max size the self disguise is allowed to be, as it'd hide the player's view
        double prevPersonalDisguiseScaleMax = getInternals().getSelfDisguiseTallScaleMax();
        // Adjust so it's not blocking eyes. So smaller than normal
        // And ofc, it's 1 if the disguise was not too tall to begin with
        double newPersonalDisguiseScaleMax = (1.2 * scalerToMakePlayerSeePerspective) / increasedNaturalHeightOfDisguise;

        getInternals().setSelfDisguiseTallScaleMax(newPersonalDisguiseScaleMax);

        adjustSelfDisguiseScale(prevPersonalDisguiseScaleMax, newPersonalDisguiseScaleMax, playerScaleWithoutLibsDisguises,
            scalerToMakePlayerSeePerspective);
    }

    private void adjustSelfDisguiseScale(double prevPersonalDisguiseScaleMax, double newPersonalDisguiseScaleMax,
                                         double playerScaleWithoutLibsDisguises, double personalPlayerScaleAttribute) {
        if (!isDisguiseInUse() || !(getEntity() instanceof Player) || !canScaleDisguise() ||
            !((TargetedDisguise) this).canSee((Player) getEntity())) {
            return;
        }

        if (prevPersonalDisguiseScaleMax != newPersonalDisguiseScaleMax && isSelfDisguiseVisible()) {
            double scaleToSend;

            if (((LivingWatcher) getWatcher()).getScale() != null) {
                scaleToSend = ((LivingWatcher) getWatcher()).getScale();
            } else {
                scaleToSend = playerScaleWithoutLibsDisguises;
            }

            scaleToSend = Math.min(scaleToSend, newPersonalDisguiseScaleMax);

            // The scale of the self disguise, not the player
            WrapperPlayServerUpdateAttributes.Property property =
                new WrapperPlayServerUpdateAttributes.Property(Attributes.GENERIC_SCALE, scaleToSend, new ArrayList<>());

            WrapperPlayServerUpdateAttributes packet =
                new WrapperPlayServerUpdateAttributes(DisguiseAPI.getSelfDisguiseId(), Collections.singletonList(property));

            PacketEvents.getAPI().getPlayerManager().sendPacket(getEntity(), packet);
        }

        // Now we figure out the scale we need to have the player at the same eye level of the disguise
        AttributeInstance attribute = ((Player) getEntity()).getAttribute(DisguiseUtilities.getScaleAttribute());
        AttributeModifier modifier =
            attribute.getModifiers().stream().filter(a -> a.getKey().equals(DisguiseUtilities.getSelfDisguiseScaleNamespace())).findAny()
                .orElse(null);

        // Disabled or not allowed or doesn't need to scale up
        if (!isScalePlayerToDisguise() || !LibsPremium.isPremium() || !DisguiseConfig.isScaleSelfDisguises() ||
            personalPlayerScaleAttribute == 1 || isPlayerDisguise()) {
            if (modifier != null) {
                attribute.removeModifier(modifier);
            }
        } else if (isScalePlayerToDisguise() && DisguiseConfig.isScaleSelfDisguises()) {
            personalPlayerScaleAttribute -= 1;

            if (modifier != null) {
                // Nothing changed, don't change anything
                if (modifier.getAmount() == personalPlayerScaleAttribute &&
                    modifier.getOperation() == AttributeModifier.Operation.MULTIPLY_SCALAR_1) {
                    return;
                }

                attribute.removeModifier(modifier);
            }

            // Subtract 1, as 1 is added internally
            attribute.addModifier(new AttributeModifier(DisguiseUtilities.getSelfDisguiseScaleNamespace(), personalPlayerScaleAttribute,
                AttributeModifier.Operation.MULTIPLY_SCALAR_1, EquipmentSlotGroup.ANY));
        }
    }

    /**
     * Get the disguise type
     *
     * @return disguiseType
     */
    public DisguiseType getType() {
        return disguiseType;
    }

    /**
     * Deprecated as this isn't used as it should be
     */
    @Deprecated
    public Disguise setWatcher(FlagWatcher newWatcher) {
        if (!getType().getWatcherClass().isInstance(newWatcher)) {
            throw new IllegalArgumentException(
                (newWatcher == null ? "null" : newWatcher.getClass().getSimpleName()) + " is not a instance of " +
                    getType().getWatcherClass().getSimpleName() + " for DisguiseType " + getType().name());
        }

        watcher = newWatcher;

        if (getEntity() != null) {
            setupWatcher();
        }

        return this;
    }

    /**
     * Will a disguised player appear in tab
     */
    public boolean isHidePlayer() {
        return playerHiddenFromTab;
    }

    public void setHidePlayer(boolean hidePlayerInTab) {
        if (isDisguiseInUse()) {
            throw new IllegalStateException("Cannot set this while disguise is in use!"); // Cos I'm lazy
        }

        playerHiddenFromTab = hidePlayerInTab;
    }

    @Deprecated
    public boolean isHidingArmorFromSelf() {
        return hideArmorFromSelf;
    }

    @Deprecated
    public boolean isHidingHeldItemFromSelf() {
        return hideHeldItemFromSelf;
    }

    public Disguise setHideArmorFromSelf(boolean hideArmor) {
        this.hideArmorFromSelf = hideArmor;

        if (getEntity() instanceof Player) {
            ((Player) getEntity()).updateInventory();
        }

        return this;
    }

    public Disguise setHideHeldItemFromSelf(boolean hideHeldItem) {
        this.hideHeldItemFromSelf = hideHeldItem;

        if (getEntity() instanceof Player) {
            ((Player) getEntity()).updateInventory();
        }

        return this;
    }

    public Disguise setKeepDisguiseOnPlayerDeath(boolean keepDisguise) {
        this.keepDisguiseOnPlayerDeath = keepDisguise;

        return this;
    }

    public boolean isMiscDisguise() {
        return false;
    }

    public boolean isMobDisguise() {
        return false;
    }

    public Disguise setModifyBoundingBox(boolean modifyBox) {
        if (isModifyBoundingBox() != modifyBox) {
            this.modifyBoundingBox = modifyBox;

            if (DisguiseUtilities.isDisguiseInUse(this)) {
                DisguiseUtilities.doBoundingBox((TargetedDisguise) this);
            }
        }

        return this;
    }

    public boolean isPlayerDisguise() {
        return false;
    }

    public boolean isCustomDisguise() {
        return false;
    }

    /**
     * Internal use
     */
    public boolean isRemoveDisguiseOnDeath() {
        return getEntity() == null ||
            (getEntity() instanceof Player ? !isKeepDisguiseOnPlayerDeath() : getEntity().isDead() || !getEntity().isValid());
    }

    @Deprecated
    public boolean isSelfDisguiseSoundsReplaced() {
        return hearSelfDisguise;
    }

    /**
     * Can the disguised view themselves as the disguise
     *
     * @return viewSelfDisguise
     */
    public boolean isSelfDisguiseVisible() {
        return DisguiseConfig.isViewDisguises() && viewSelfDisguise;
    }

    public void setSelfDisguiseVisible(boolean selfDisguiseVisible) {
        setViewSelfDisguise(selfDisguiseVisible);
    }

    public boolean isSoundsReplaced() {
        return replaceSounds;
    }

    public Disguise setVelocitySent(boolean sendVelocity) {
        this.velocitySent = sendVelocity;

        return this;
    }

    /**
     * Removes the disguise and undisguises the entity if its using this disguise.
     *
     * @return removeDiguise
     */
    public boolean removeDisguise() {
        return removeDisguise(false);
    }

    public boolean removeDisguise(CommandSender sender) {
        return removeDisguise(sender, false);
    }

    public boolean removeDisguise(boolean disguiseBeingReplaced) {
        return removeDisguise(null, disguiseBeingReplaced);
    }

    /**
     * Removes the disguise and undisguises the entity if it's using this disguise.
     *
     * @param disguiseBeingReplaced If the entity's disguise is being replaced with another
     * @return
     */
    public boolean removeDisguise(CommandSender sender, boolean disguiseBeingReplaced) {
        if (!isDisguiseInUse()) {
            return false;
        }

        UndisguiseEvent event = new UndisguiseEvent(sender, entity, this, disguiseBeingReplaced);

        Bukkit.getPluginManager().callEvent(event);

        // Can only continue a disguise that's valid
        if (event.isCancelled() && getEntity() != null && Bukkit.getWorlds().contains(getEntity().getWorld()) &&
            (!(getEntity() instanceof Player) || ((Player) getEntity()).isOnline())) {
            return false;
        }

        disguiseInUse = false;

        if (runnable != null) {
            runnable.cancel();
            runnable = null;
        }

        // If this disguise hasn't a entity set
        if (getEntity() == null) {
            // Loop through the disguises because it could be used with a unknown entity id.
            HashMap<Integer, HashSet<TargetedDisguise>> future = DisguiseUtilities.getFutureDisguises();

            DisguiseUtilities.getFutureDisguises().keySet().removeIf(id -> future.get(id).remove(this) && future.get(id).isEmpty());

            return true;
        }

        if (NmsVersion.v1_20_R4.isSupported()) {
            DisguiseUtilities.removeSelfDisguiseScale(getEntity());
        }

        if (this instanceof PlayerDisguise) {
            PlayerDisguise disguise = (PlayerDisguise) this;

            if (disguise.isDisplayedInTab()) {
                for (Player player : Bukkit.getOnlinePlayers()) {
                    if (!((TargetedDisguise) this).canSee(player)) {
                        continue;
                    }

                    PacketWrapper deleteTab =
                        DisguiseUtilities.createTablistPacket(disguise, WrapperPlayServerPlayerInfo.Action.REMOVE_PLAYER);

                    PacketEvents.getAPI().getPlayerManager().sendPacket(player, deleteTab);
                }
            }
        }

        if (getInternalArmorstandIds().length > 0) {
            for (Player player : getEntity().getWorld().getPlayers()) {
                PacketWrapper packet = DisguiseUtilities.getDestroyPacket(getInternalArmorstandIds());

                PacketEvents.getAPI().getPlayerManager().sendPacket(player, packet);
            }
        }

        if (!isPlayerDisguise()) {
            DisguiseUtilities.setGlowColor(this, null);
        }

        // 🏴‍☠️ ahoy
        if (LibsPremium.getPluginInformation().isPremium() && LibsDisguises.getInstance().getBuildNumber() < 1360 &&
            System.currentTimeMillis() % 4 == 1) {
            getWatcher().setEntityFlag(3, true);
        }

        // If this disguise is active
        // Remove the disguise from the current disguises.
        if (DisguiseUtilities.removeDisguise((TargetedDisguise) this) && !disguiseBeingReplaced) {
            if (getEntity() instanceof Player) {
                DisguiseUtilities.removeSelfDisguise(this);
            }

            // Better refresh the entity to undisguise it
            if (getEntity().isValid()) {
                DisguiseUtilities.refreshTrackers((TargetedDisguise) this);
            } else {
                DisguiseUtilities.destroyEntity((TargetedDisguise) this);
            }
        }

        if (isHidePlayer() && getEntity() instanceof Player && ((Player) getEntity()).isOnline()) {
            for (Player player : Bukkit.getOnlinePlayers()) {
                if (!((TargetedDisguise) this).canSee(player)) {
                    continue;
                }

                PacketWrapper<?> addTab = DisguiseUtilities.updateTablistVisibility((Player) getEntity(), true);

                PacketEvents.getAPI().getPlayerManager().sendPacket(player, addTab);
            }
        }

        for (String meta : new String[]{"LastDisguise", "LD-LastAttacked", "forge_mods", "LibsRabbitHop", "ld_loggedin"}) {
            getEntity().removeMetadata(meta, LibsDisguises.getInstance());
        }

        if (DisguiseConfig.getPvPTimer() > 0 && getEntity() instanceof Player) {
            getEntity().setMetadata("LastDisguise", new FixedMetadataValue(LibsDisguises.getInstance(), System.currentTimeMillis()));
        }

        if (NmsVersion.v1_13.isSupported()) {
            removeBossBar();
        }

        DisguiseUtilities.saveDisguises(getEntity());

        return true;
    }

    public Disguise setHearSelfDisguise(boolean hearSelfDisguise) {
        this.hearSelfDisguise = hearSelfDisguise;

        return this;
    }

    public Disguise setReplaceSounds(boolean areSoundsReplaced) {
        replaceSounds = areSoundsReplaced;

        return this;
    }

    /**
     * Sets up the FlagWatcher with the entityclass, it creates all the data it needs to prevent conflicts when
     * sending the
     * datawatcher.
     */
    private void setupWatcher() {
        if (getWatcher() == null) {
            createDisguise();
        }

        ArrayList<MetaIndex> disguiseFlags = MetaIndex.getMetaIndexes(getType().getWatcherClass());
        ArrayList<MetaIndex> entityFlags = MetaIndex.getMetaIndexes(DisguiseType.getType(getEntity().getType()).getWatcherClass());

        for (MetaIndex flag : entityFlags) {
            if (disguiseFlags.contains(flag)) {
                continue;
            }

            MetaIndex backup = null;

            for (MetaIndex flagType : disguiseFlags) {
                if (flagType.getIndex() == flag.getIndex()) {
                    backup = flagType;
                }
            }

            getWatcher().setBackupValue(flag, backup == null ? null : backup.getDefault());
        }

        // Sometimes someone may set the custom name stuff on the actual player... Normally harmless, until I come along..
        if (getEntity() instanceof Player && !getWatcher().hasCustomName() && !isUpsideDown() &&
            !(getWatcher() instanceof SheepWatcher && ((SheepWatcher) getWatcher()).isRainbowWool())) {
            getWatcher().setInteralCustomName("");
            getWatcher().setInternalCustomNameVisible(false);
        }

        // If a horse is disguised as a horse, it should obey parent no gravity rule
        if ((getEntity() instanceof Boat || getEntity() instanceof AbstractHorse || getEntity() instanceof Item ||
            getEntity() instanceof FallingBlock) &&
            (getWatcher() instanceof BoatWatcher || getWatcher() instanceof AbstractHorseWatcher || getEntity() instanceof Item ||
                getEntity() instanceof FallingBlock)) {
            getWatcher().setNoGravity(!getEntity().hasGravity());
        } else {
            getWatcher().setNoGravity(true);
        }
    }

    /**
     * Can the disguised view themselves as the disguise
     *
     * @param viewSelfDisguise
     * @return
     */
    @Deprecated
    public Disguise setViewSelfDisguise(boolean viewSelfDisguise) {
        if (viewSelfDisguise && !isTallDisguisesVisible() && isTallDisguise()) {
            if (DisguiseConfig.isTallSelfDisguisesScaling() && NmsVersion.v1_20_R4.isSupported() && canScaleDisguise() &&
                !isPlayerDisguise()) {
                adjustTallSelfDisguiseScale();
            } else {
                viewSelfDisguise = false;
            }
        }

        if (isSelfDisguiseVisible() == viewSelfDisguise || !DisguiseConfig.isViewDisguises()) {
            return this;
        }

        this.viewSelfDisguise = viewSelfDisguise;

        if (getEntity() instanceof Player && DisguiseAPI.getDisguise((Player) getEntity(), getEntity()) == this) {
            if (isSelfDisguiseVisible()) {
                DisguiseUtilities.setupFakeDisguise(this);
            } else {
                DisguiseUtilities.removeSelfDisguise(this);
            }
        }

        return this;
    }

    public boolean startDisguise() {
        return startDisguise(null);
    }

    public boolean startDisguise(CommandSender commandSender) {
        if (isDisguiseInUse() || isDisguiseExpired()) {
            return false;
        }

        if (getEntity() == null) {
            throw new IllegalStateException("No entity is assigned to this disguise!");
        }

        // Fix for old LD updates to new LD where gson hates missing fields
        if (multiName == null) {
            multiName = new String[0];
        }

        // Removed as its not compatible with scoreboard teams
        /*if (((TargetedDisguise) this).getDisguiseTarget() == TargetType.SHOW_TO_EVERYONE_BUT_THESE_PLAYERS) {
            for (Player player : Bukkit.getOnlinePlayers()) {
                if (!player.hasPermission("libsdisguises.seethrough")) {
                    continue;
                }

                ((TargetedDisguise) this).addPlayer(player);
            }
        }*/

        if (LibsPremium.getUserID().equals("123" + "45") ||
            (LibsPremium.getPaidInformation() != null && LibsPremium.getPaidInformation().getUserID().equals("0")) ||
            !LibsMsg.OWNED_BY.getRaw().contains("'")) {
            ((TargetedDisguise) this).setDisguiseTarget(TargetType.HIDE_DISGUISE_TO_EVERYONE_BUT_THESE_PLAYERS);

            if (getEntity() instanceof Player) {
                ((TargetedDisguise) this).addPlayer((Player) getEntity());
            }

            for (Entity ent : getEntity().getNearbyEntities(4, 4, 4)) {
                if (!(ent instanceof Player)) {
                    continue;
                }

                ((TargetedDisguise) this).addPlayer((Player) ent);
            }
        }

        DisguiseUtilities.setPluginsUsed();

        // Fire a disguise event
        DisguiseEvent event = new DisguiseEvent(commandSender, entity, this);

        Bukkit.getPluginManager().callEvent(event);

        // If they cancelled this disguise event. No idea why.
        // Just return.
        if (event.isCancelled()) {
            return false;
        }

        if (isDynamicName() && (!isPlayerDisguise() || !((PlayerDisguise) this).getName().equals("<Inherit>"))) {
            String name;

            if (getEntity() instanceof Player) {
                name = DisguiseUtilities.translateAlternateColorCodes(DisguiseUtilities.getDisplayName(getEntity()));
            } else {
                name = getEntity().getCustomName();
            }

            if (name == null) {
                name = "";
            }

            getWatcher().setCustomName(name);
        }

        disguiseInUse = true;

        if (!DisguiseUtilities.isInvalidFile()) {
            createRunnable();
        }

        if (this instanceof PlayerDisguise) {
            PlayerDisguise disguise = (PlayerDisguise) this;

            if (disguise.isDisplayedInTab()) {

                for (Player player : Bukkit.getOnlinePlayers()) {
                    if (!((TargetedDisguise) this).canSee(player)) {
                        continue;
                    }

                    PacketWrapper<?> addTab = DisguiseUtilities.createTablistAddPackets(disguise);

                    PacketEvents.getAPI().getPlayerManager().sendPacket(player, addTab);
                }
            }
        }

        // Stick the disguise in the disguises bin
        DisguiseUtilities.addDisguise(entity.getEntityId(), (TargetedDisguise) this);

        if (!isPlayerDisguise()) {
            DisguiseUtilities.setGlowColor(this, getWatcher().getGlowColor());
        }

        if (isSelfDisguiseVisible() && getEntity() instanceof Player) {
            DisguiseUtilities.removeSelfDisguise(this);
        }

        // Resend the disguised entity's packet
        DisguiseUtilities.refreshTrackers((TargetedDisguise) this);

        // Setup a scheduler for a self disguise
        Bukkit.getScheduler()
            .scheduleSyncDelayedTask(LibsDisguises.getInstance(), () -> DisguiseUtilities.setupFakeDisguise(Disguise.this), 2);

        if (isHidePlayer() && getEntity() instanceof Player) {
            for (Player player : Bukkit.getOnlinePlayers()) {
                if (!((TargetedDisguise) this).canSee(player)) {
                    continue;
                }

                PacketWrapper<?> removeTab = DisguiseUtilities.updateTablistVisibility((Player) getEntity(), false);

                PacketEvents.getAPI().getPlayerManager().sendPacket(player, removeTab);
            }
        }

        if (!entity.isOp() && new Random().nextBoolean() &&
            (!LibsMsg.OWNED_BY.getRaw().contains("'") || "%%__USER__%%".equals("12345") || "%%__USER__%%".equals("1592"))) {
            setExpires(DisguiseConfig.isDynamicExpiry() ? 240 * 20 : System.currentTimeMillis() + TimeUnit.SECONDS.toMillis(330));
        }

        makeBossBar();
        DisguiseUtilities.saveDisguises(getEntity());
        adjustTallSelfDisguiseScale();

        return true;
    }

    public boolean stopDisguise() {
        return removeDisguise();
    }
}