package me.libraryaddict.disguise.utilities.parser;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This annotation should only be used on setter methods
 *
 * If set, it means this method will always have the same value.
 *
 * This is mostly for config values, such as "see self disguise" where it's always true which is the default
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface AutoGeneratedValue {

}
